<a href="https://colab.research.google.com/github/PeteJoh/fpl-ai/blob/master/train_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#------------------------------------------------------
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [98]:
forward_statistics =['value', 'was_home', 'last_season_position', 'percent_value',
       'position rank', 'goals_scored_ex', 'assists_ex', 'total_points_ex',
       'minutes_ex', 'goals_conceded_ex', 'creativity_ex', 'influence_ex',
       'threat_ex', 'bonus_ex', 'bps_ex', 'ict_index_ex', 'now_cost_ex', 'GW', 'opponent_last_season_position',
        'mean assists 3','mean bonus 3', 'mean bps 3','mean creativity 3', 'mean goals_scored 3',
       'mean ict_index 3', 'mean influence 3', 'mean minutes 3', 'mean penalties_missed 3',  'mean threat 3',
       'mean total_points 3','mean value 3', 'mean match_result 3', 'std bps 3', 'std creativity 3',
       'std ict_index 3', 'std influence 3', 'std minutes 3',
       'std threat 3', 'std total_points 3', 'std value 3']

leak_columns = [
    "name",
    "team",
]  # columns that shouldnt be used in training fir fear of data leakage


dropped_columns = [
    "season",
    "opponent",
    "match_result",
   # "position",
    "assists",
    "penalties_missed",
    "bonus",
    "bps",
    "clean_sheets",
    "creativity",
    "goals_conceded",
    "goals_scored",
    "ict_index",
    "influence",
    "own_goals",
    "penalties_saved",
    "red_cards",
    "saves",
    "selected",
    "threat",
    "transfers_balance",
    "transfers_in",
    "transfers_out",
    "yellow_cards",
    "team Goal scored",
    "team Goal conceded"
]  # "value",

midfielder_statistics =['value', 'was_home', 'last_season_position', 'percent_value',
       'position rank', 'goals_scored_ex', 'assists_ex', 'total_points_ex',
       'minutes_ex', 'goals_conceded_ex', 'creativity_ex', 'influence_ex',
       'threat_ex', 'bonus_ex', 'bps_ex', 'ict_index_ex', 'now_cost_ex', 'GW', 'opponent_last_season_position',
        'mean assists 3','mean bonus 3', 'mean bps 3','mean creativity 3', 'mean goals_scored 3',
       'mean ict_index 3', 'mean influence 3', 'mean minutes 3', 'mean penalties_missed 3',  'mean threat 3',
       'mean total_points 3','mean value 3', 'mean match_result 3', 'std bps 3', 'std creativity 3',
       'std ict_index 3', 'std influence 3', 'std minutes 3',
       'std threat 3', 'std total_points 3', 'std value 3']

goalkeeper_statistics = ['value', 'was_home', 'last_season_position', 'percent_value',
       'position rank', 'total_points_ex', 'minutes_ex', 'goals_conceded_ex',
       'bonus_ex', 'bps_ex', 'ict_index_ex', 'clean_sheets_ex',
       'red_cards_ex', 'now_cost_ex', 'GW', 'opponent_last_season_position',
       'mean bonus 3', 'mean bps 3', 'mean clean_sheets 3', 'mean goals_conceded 3',
       'mean ict_index 3',  'mean minutes 3',
       'mean own_goals 3',  'mean penalties_saved 3',
        'mean saves 3',  'mean threat 3',
       'mean total_points 3',
       'mean value 3', 'mean match_result 3', 'std bps 3',
       'std ict_index 3', 'std influence 3', 'std minutes 3',
       'std threat 3', 'std total_points 3', 'std value 3']

statistics =['value', 'position','was_home', 'last_season_position', 'percent_value',
       'position rank', 'goals_scored_ex', 'assists_ex', 'total_points_ex',
       'minutes_ex', 'goals_conceded_ex', 'creativity_ex', 'influence_ex',
       'threat_ex', 'bonus_ex', 'bps_ex', 'ict_index_ex', 'clean_sheets_ex',
       'yellow_cards_ex','now_cost_ex', 'GW', 'opponent_last_season_position', 'mean assists 3',
       'mean bonus 3', 'mean bps 3', 'mean clean_sheets 3',
       'mean creativity 3', 'mean goals_conceded 3', 'mean goals_scored 3',
       'mean ict_index 3', 'mean influence 3', 'mean minutes 3',
       'mean own_goals 3',
       'mean red_cards 3',  'mean threat 3','mean total_points 3',
       'mean value 3', 'mean match_result 3', 'std bps 3', 'std creativity 3',
       'std ict_index 3', 'std influence 3', 'std minutes 3',
       'std threat 3', 'std total_points 3', 'std value 3','mean saves 3','mean assists all',
       'mean bonus all', 'mean bps all', 'mean clean_sheets all',
       'mean creativity all', 'mean goals_conceded all', 'mean goals_scored all',
       'mean ict_index all', 'mean influence all', 'mean minutes all',
       'mean own_goals all',
       'mean red_cards all',  'mean threat all','mean total_points all',
       'mean value all', 'mean match_result all',
       'mean team Goal scored 3','mean team Goal scored all','mean team Goal conceded 3','mean team Goal conceded all',"ratio_goal_scored all","ratio_goal_scored 3",
       'opp mean team Goal scored 3','opp mean team Goal conceded 3','opp mean team Goal scored all','opp mean team Goal conceded all',"opp mean match_result all"]


date_cols=["day_of week","month","hour","week"]

In [99]:
def convert_minutes(val):
    """CONVERTS MINUTES TO A CATEGORICAL OUTPUT"""
    if val > 10:
        return 1
    else:
        return 0

In [70]:
pip install catboost

In [71]:
from hyperopt import tpe,hp,fmin,STATUS_OK,Trials
from hyperopt.pyll.base import scope

In [100]:
import pandas as pd
import numpy as np
import warnings
import os


warnings.filterwarnings("ignore")
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.ensemble import (
    RandomForestClassifier,
    RandomForestRegressor,
    GradientBoostingRegressor,
)
from sklearn.preprocessing import StandardScaler, RobustScaler, MinMaxScaler
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.metrics import (
    mean_squared_error,
    mean_absolute_error,
    confusion_matrix,
    accuracy_score,
    f1_score,
)
from lightgbm import LGBMRegressor, LGBMClassifier
from catboost import CatBoostClassifier, CatBoostRegressor
from sklearn.model_selection import StratifiedKFold,KFold

In [125]:
gameweek=10

In [126]:
# RELOAD THIS DATA FOR EACH MODEL

train = pd.read_csv("/content/gdrive/MyDrive/fplpredict/cleaned_dataset/cleaned_previous_seasons.csv",index_col=0)#/content/drive/MyDrive/Fplpredict /cleaned_previous_seasons.csv", index_col=0)
old_gameweek_cleaned = []
for i in range(1, gameweek):
    old_gameweek_cleaned.append(pd.read_csv(f"/content/gdrive/MyDrive/fplpredict/cleaned_dataset/2024-25/GW{i}.csv"))
old_gameweeks = pd.concat(old_gameweek_cleaned)[train.columns]
train = pd.concat([train, old_gameweeks])

# data for current gameweek we want to predict on
test = pd.read_csv(f"/content/gdrive/MyDrive/fplpredict/cleaned_dataset/2024-25/GW{gameweek}.csv", index_col=0)

In [103]:
#CREATE GAMEWEEK PREDICTIONS FOLDER
path = f"/content/gdrive/MyDrive/fplpredict/predicted_dataset/GW{gameweek}"

# create new single directory
# check whether directory already exists
if not os.path.exists(path):
    os.mkdir(path)
    print("Folder %s created!" % path)
else:
    print("Folder %s already exists" % path)

# data from current season but previous gameweeks

Folder /content/gdrive/MyDrive/fplpredict/predicted_dataset/GW10 already exists


In [127]:
train["position"].value_counts()

position
MID    52571
DEF    42209
FWD    15724
GK     13166
GKP      767
Name: count, dtype: int64

In [128]:
train["position"]=train["position"].replace({"GKP":"GK" })

In [129]:
# MINUTES PREDICTOR STARTS HERE************************************************
# Ensure both DataFrames have the same columns before alignment
# Create the date-related columns in 'test' first
import pandas as pd
from sklearn.model_selection import train_test_split

test["index"] = test["name"] + test["kickoff_time"].astype("str")
test = test.set_index("index")
test["date"] = pd.to_datetime(test["kickoff_time"], format='ISO8601', errors='coerce')
test["day_of week"] = test["date"].dt.day_name()  # Added parentheses to call the function
test["month"] = test["date"].dt.month
test["hour"] = test["date"].dt.hour
test["week"] = test["date"].dt.isocalendar().week
test.drop(["kickoff_time", "date"], axis=1, inplace=True)

# Now process 'train' DataFrame
# Create 'index' column *before* dropping 'kickoff_time'
train["index"] = train["name"] + train["kickoff_time"].astype("str")
train.drop_duplicates("index", keep="last", inplace=True)
train = train.set_index("index")

# Now you can create date features and then drop 'kickoff_time'
train["date"] = pd.to_datetime(train["kickoff_time"], format='ISO8601', errors='coerce')
train["day_of week"] = train["date"].dt.day_name()  # Added parentheses to call the function
train["month"] = train["date"].dt.month
train["hour"] = train["date"].dt.hour
train["week"] = train["date"].dt.isocalendar().week
train.drop(["kickoff_time", "date"], axis=1, inplace=True) # Now safe to drop


#Keep only common columns in both dataframes
common_cols = list(set(train.columns) & set(test.columns))

train = train[common_cols]
test = test[common_cols]



train_copy = train.copy()
test_copy = test.copy()


train["minutes"] = train["minutes"].apply(convert_minutes)

target = train[["minutes", "GW", "position"]]
train.drop(["total_points", "minutes"], axis=1, inplace=True)
test.drop(["total_points", "minutes"], axis=1, inplace=True)
train.drop(dropped_columns, axis=1, inplace=True)
test.drop(dropped_columns, axis=1, inplace=True)


# Convert categorical columns to numerical
for col in train.columns:
    if train[col].dtype == "object":
        if col not in ["team", "name", "position"]:
            train[col] = pd.factorize(train[col])[0]
            test[col] = pd.factorize(test[col])[0]

train["was_home"] = train["was_home"].replace({True: 0, False: 1})
test["was_home"] = test["was_home"].replace({True: 0, False: 1})

train = train[statistics + leak_columns + date_cols]
test = test[statistics + leak_columns + date_cols]

x, val, y, y_val = train_test_split(
    train.drop(leak_columns, axis=1),
    target["minutes"],
    test_size=0.1,
    random_state=0,
)

In [130]:
params={'colsample_bylevel': 0.8070621518153563, 'learning_rate': 0.04765984972709895, 'max_depth': 7, 'reg_lambda': 5, 'scale_pos_weight': 2.5,'subsample': 0.6794390204583894}
model=CatBoostClassifier(**params,cat_features=["position"],random_state=0,early_stopping_rounds=500,use_best_model=True,verbose=500,n_estimators=10000)

In [131]:
model.fit(x, y,eval_set=[(val,y_val)])

0:	learn: 0.6525880	test: 0.6526917	best: 0.6526917 (0)	total: 127ms	remaining: 21m 9s
500:	learn: 0.2974733	test: 0.3179153	best: 0.3179153 (500)	total: 1m 16s	remaining: 24m 14s
1000:	learn: 0.2735103	test: 0.3177685	best: 0.3176982 (972)	total: 2m 34s	remaining: 23m 6s
Stopped by overfitting detector  (500 iterations wait)

bestTest = 0.3176981932
bestIteration = 972

Shrink model to first 973 iterations.


In [132]:
print(confusion_matrix(model.predict(val), y_val))
print(
    f"starting Accuracy score {accuracy_score(model.predict(val), y_val)}"
)

print(
    f" starting f1 score: {f1_score(model.predict(val), y_val)}"
)

feature_importance = pd.DataFrame(
    {"column": x.columns, "imp": model.feature_importances_}
).sort_values(
    "imp", ascending=False
)  #

[[5495  375]
 [1401 3920]]
starting Accuracy score 0.8413010454829773
 starting f1 score: 0.8153078202995009


[[3863  267]
 [ 975 2862]]
starting Accuracy score 0.8441069411321702
 starting f1 score: 0.8217054263565893

In [ ]:
feature_importance.head(50)

In [ ]:
feature_importance.tail(20)

In [ ]:
y_val

In [135]:
test_copy["minutes"] = model.predict(test.drop(leak_columns, axis=1))
test_copy[leak_columns + ["minutes"]].to_csv(
    f"minutes.csv"
)

In [136]:
predicted_minutes=model.predict(val)
val_=pd.DataFrame({"ind":val.index,"actul_minutes":y_val,"predicted_minutes":predicted_minutes,"position":val["position"]})

In [137]:
print(f"STARTING GOALKEEPERS PERFORMANCE!!!")
a=val_[val_["position"]=="GK"]["actul_minutes"]
b=val_[val_["position"]=="GK"]["predicted_minutes"]
print(confusion_matrix(a,b))
print(
    f"starting Accuracy score {accuracy_score(a,b)}"
)

print(
    f" starting f1 score: {f1_score(a,b)}"
)

STARTING GOALKEEPERS PERFORMANCE!!!
[[793  44]
 [ 27 324]]
starting Accuracy score 0.9402356902356902
 starting f1 score: 0.9012517385257302


STARTING GOALKEEPERS PERFORMANCE!!!
[[583  21]
 [ 24 216]]
starting Accuracy score 0.9466824644549763
 starting f1 score: 0.9056603773584907

STARTING DEFENDERS PERFORMANCE!!!
[[1449  208]
 [ 200  915]]
starting Accuracy score 0.8528138528138528
 starting f1 score: 0.817694369973190

STARTING MIDFIELDERS PERFORMANCE!!!
[[1595  288]
 [ 235 1195]]
starting Accuracy score 0.8421370359191066
 starting f1 score: 0.820460006865774

STARTING FORWARDS PERFORMANCE!!!
[[497  88]
 [ 69 325]]
starting Accuracy score 0.839632277834525
 starting f1 score: 0.8054522924411399

In [138]:
print(f"STARTING DEFENDERS PERFORMANCE!!!")
a=val_[val_["position"]=="DEF"]["actul_minutes"]
b=val_[val_["position"]=="DEF"]["predicted_minutes"]
print(confusion_matrix(a,b))
print(
    f"starting Accuracy score {accuracy_score(a,b)}"
)

print(
    f" starting f1 score: {f1_score(a,b)}"
)

STARTING DEFENDERS PERFORMANCE!!!
[[1843  543]
 [ 146 1282]]
starting Accuracy score 0.819349764027268
 starting f1 score: 0.7881955118352291


In [139]:
print(f"STARTING MIDFIELDERS PERFORMANCE!!!")
a=val_[val_["position"]=="MID"]["actul_minutes"]
b=val_[val_["position"]=="MID"]["predicted_minutes"]
print(confusion_matrix(a,b))
print(
    f"starting Accuracy score {accuracy_score(a,b)}"
)

print(
    f" starting f1 score: {f1_score(a,b)}"
)

STARTING MIDFIELDERS PERFORMANCE!!!
[[2185  630]
 [ 148 1821]]
starting Accuracy score 0.8373745819397993
 starting f1 score: 0.8239819004524886


In [140]:
print(f"STARTING FORWARDS PERFORMANCE!!!")
a=val_[val_["position"]=="FWD"]["actul_minutes"]
b=val_[val_["position"]=="FWD"]["predicted_minutes"]
print(confusion_matrix(a,b))
print(
    f"starting Accuracy score {accuracy_score(a,b)}"
)

print(
    f" starting f1 score: {f1_score(a,b)}"
)

STARTING FORWARDS PERFORMANCE!!!
[[674 184]
 [ 54 493]]
starting Accuracy score 0.8306049822064057
 starting f1 score: 0.8055555555555556


In [141]:
test_copy[test_copy["minutes"]==1]["position"].value_counts()

position
MID    169
DEF    114
FWD     37
GKP     24
Name: count, dtype: int64

In [142]:
train = train_copy[train_copy["minutes"] > 0]
test = test_copy[test_copy["minutes"] > 0]

# MINUTES PREDICTION ENDS HERE - MAKE SURE TO SAVE MINUTES PREDICTIONS AT THE BOTTOM OF THE SCRIPT

In [111]:
#Predict Points - MAKE SURE TO READ THE DATA IN AGAIN

train["index"] = train["name"] + train["kickoff_time"].astype("str")
train.drop_duplicates("index", keep="last", inplace=True)
train= train.set_index("index")
#train["date"]=pd.to_datetime(train["kickoff_time"])
train["date"] = pd.to_datetime(train["kickoff_time"], format='ISO8601', errors='coerce')
#train["day_of week"]=train["date"].dt.day_name
train["day_of week"] = train["date"].dt.day_name()  # Added parentheses to call the function
train["month"]=train["date"].dt.month
train["hour"]=train["date"].dt.hour
#train["week"]=train["date"].dt.week
train["week"] = train["date"].dt.isocalendar().week
train.drop(["kickoff_time","date"], axis=1, inplace=True)

test["index"] = test["name"] + test["kickoff_time"].astype("str")
test = test.set_index("index")
#test["date"]=pd.to_datetime(test["kickoff_time"])
test["date"] = pd.to_datetime(test["kickoff_time"], format='ISO8601', errors='coerce')
#test["day_of week"]=test["date"].dt.day_name
test["day_of week"] = test["date"].dt.day_name()  # Added parentheses to call the function
test["month"]=test["date"].dt.month
test["hour"]=test["date"].dt.hour
#test["week"]=test["date"].dt.week
test["week"] = test["date"].dt.isocalendar().week
test.drop(["kickoff_time","date"], axis=1, inplace=True)

target = train[["total_points", "GW","position" ]]
train.drop(["total_points", "minutes"], axis=1, inplace=True)
test.drop(["total_points", "minutes"], axis=1, inplace=True)
train.drop(dropped_columns, axis=1, inplace=True)
test.drop(dropped_columns, axis=1, inplace=True)


for col in train.columns:
    if train[col].dtype == "object":
        if col not in ["team", "name","position"]:
            train[col] = pd.factorize(train[col])[0]
            test[col] = pd.factorize(test[col])[0]

train["position"]=train["position"].astype("category")
test["position"]=test["position"].astype("category")
train["was_home"] = train["was_home"].replace({True: 0, False: 1})
test["was_home"] = test["was_home"].replace({True: 0, False: 1})

train = train[statistics + leak_columns+date_cols]
test= test[statistics + leak_columns+date_cols]

x, val, y, y_val = train_test_split(
    train.drop(leak_columns, axis=1),
    target["total_points"],
    test_size=0.1,
    random_state=0,
)

In [112]:
from sklearn.model_selection import KFold

#cross_validator to splite the data into folds
folds=KFold(n_splits=8,shuffle=True,random_state=0)

#a dataframe to store the predictions made by each fold
predictions_df=pd.DataFrame()

#list to save the mean absolute errors from validatingon each folds
rmse_val=[]
rmse_X=[]

#a simple catboost regressor
model=LGBMRegressor(**{'colsample_bytree': 0.4199299182268318, 'learning_rate': 0.0032874466037521254, 'max_depth': 9, 'min_split_gain': 0.5685369160138952, 'num_leaves': 99, 'reg_alpha': 0.5621526419488447, 'reg_lambda': 0, 'subsample': 0.6534153111773866}, verbose=-50,random_state=0,early_stopping_rounds=200,n_estimators=10000)

#train model, make predictions and check the validation accuracy on  each fold
for i,(train_index,test_index) in enumerate(folds.split(train.drop(leak_columns, axis=1),target["total_points"])):
    train_fold=train.drop(leak_columns, axis=1).iloc[train_index]
    val_fold=train.drop(leak_columns, axis=1).iloc[test_index]
    y_fold=target["total_points"].iloc[train_index]
    y_val_fold=target["total_points"].iloc[test_index]


    model.fit(train_fold,y_fold,eval_set=[(val_fold,y_val_fold)])
    print(i+1)
    prediction=model.predict(test.drop(leak_columns, axis=1))
    predictions_df[i]=prediction
    rmse_val.append(mean_squared_error(model.predict(val_fold),y_val_fold,squared=False))
    rmse_X.append(mean_squared_error(model.predict(train_fold),y_fold,squared=False))
print(rmse_val)
print(rmse_X)

1
2
3
4
5
6
7
8
[1.9946393170356036, 1.9546758580015136, 1.9780176949173842, 1.951287106223024, 2.004787998844915, 1.97115242637412, 1.959004215500157, 1.9723968096208457]
[1.454531659417867, 1.5038361988405857, 1.5270988350311632, 1.3766886402265621, 1.399895350872374, 1.490484348292099, 1.529895375944153, 1.7247040730961758]


In [113]:
print(np.mean(rmse_val))
print(np.mean(rmse_X))
#2.7575293874474336
#2.0174134721607295

1.9732451783146954
1.5008918102151225


2.7320675301713573
1.6917027774360753

In [114]:
predictions_df[0]

0      0.023224
1      0.989653
2      0.056020
3      0.043454
4      2.557844
         ...   
665    1.596976
666    2.271958
667    0.348180
668    4.683585
669    0.032784
Name: 0, Length: 670, dtype: float64

In [115]:
test["points"]=np.mean(predictions_df, axis=1).values

test[leak_columns + ["points", "value"]].sort_values(
    "points", ascending=False
).to_csv("points.csv")

In [116]:
test[test["position"]=="MID"].sort_values(by="points",ascending=False).head(11)[["name","points","team"]]

name    points  \
index                                                                          
Mohamed Salah2024-11-02T15:00:00Z                    Mohamed Salah  7.046866   
Bukayo Saka2024-11-02T12:30:00Z                        Bukayo Saka  5.566477   
Bryan Mbeumo2024-11-04T20:00:00Z                      Bryan Mbeumo  4.812529   
Cole Palmer2024-11-03T16:30:00Z                        Cole Palmer  4.477835   
Declan Rice2024-11-02T12:30:00Z                        Declan Rice  4.459019   
Brennan Johnson2024-11-03T14:00:00Z                Brennan Johnson  4.187138   
Eberechi Eze2024-11-02T17:30:00Z                      Eberechi Eze  4.182510   
Jarrod Bowen2024-11-02T15:00:00Z                      Jarrod Bowen  4.021720   
Mikkel Damsgaard2024-11-04T20:00:00Z              Mikkel Damsgaard  3.893360   
Dwight McNeil2024-11-02T15:00:00Z                    Dwight McNeil  3.871607   
Bruno Borges Fernandes2024-11-03T16:30:00Z  Bruno Borges Fernandes  3.686618   

                                                      team  
index                                                       
Mohamed Salah2024-11-02T15:00:00Z                Liverpool  
Bukayo Saka2024-11-02T12:30:00Z                    Arsenal  
Bryan Mbeumo2024-11-04T20:00:00Z                 Brentford  
Cole Palmer2024-11-03T16:30:00Z                    Chelsea  
Declan Rice2024-11-02T12:30:00Z                    Arsenal  
Brennan Johnson2024-11-03T14:00:00Z                  Spurs  
Eberechi Eze2024-11-02T17:30:00Z            Crystal Palace  
Jarrod Bowen2024-11-02T15:00:00Z                  West Ham  
Mikkel Damsgaard2024-11-04T20:00:00Z             Brentford  
Dwight McNeil2024-11-02T15:00:00Z                  Everton  
Bruno Borges Fernandes2024-11-03T16:30:00Z         Man Utd

In [117]:
test[test["position"]=="DEF"].sort_values(by="points",ascending=False).head(10)[["name","points","team"]]

name  \
index                                                                                   
Trent Alexander-Arnold2024-11-02T15:00:00Z                     Trent Alexander-Arnold   
Rayan Aït-Nouri2024-11-02T17:30:00Z                                   Rayan Aït-Nouri   
Joško Gvardiol2024-11-02T15:00:00Z                                     Joško Gvardiol   
Ashley Young2024-11-02T15:00:00Z                                         Ashley Young   
Ethan Pinnock2024-11-04T20:00:00Z                                       Ethan Pinnock   
Leif Davis2024-11-02T15:00:00Z                                             Leif Davis   
Murillo Santiago Costa dos Santos2024-11-02T15:...  Murillo Santiago Costa dos Santos   
Ola Aina2024-11-02T15:00:00Z                                                 Ola Aina   
Nélson Cabral Semedo2024-11-02T17:30:00Z                         Nélson Cabral Semedo   
Pedro Porro2024-11-03T14:00:00Z                                           Pedro Porro   

                                                      points           team  
index                                                                        
Trent Alexander-Arnold2024-11-02T15:00:00Z          3.686967      Liverpool  
Rayan Aït-Nouri2024-11-02T17:30:00Z                 3.640290         Wolves  
Joško Gvardiol2024-11-02T15:00:00Z                  3.541818       Man City  
Ashley Young2024-11-02T15:00:00Z                    3.497327        Everton  
Ethan Pinnock2024-11-04T20:00:00Z                   3.232022      Brentford  
Leif Davis2024-11-02T15:00:00Z                      3.206921        Ipswich  
Murillo Santiago Costa dos Santos2024-11-02T15:...  3.121346  Nott'm Forest  
Ola Aina2024-11-02T15:00:00Z                        3.111873  Nott'm Forest  
Nélson Cabral Semedo2024-11-02T17:30:00Z            3.062821         Wolves  
Pedro Porro2024-11-03T14:00:00Z                     2.994397          Spurs

In [118]:
test[test["position"]=="GKP"].sort_values(by="points",ascending=False).head(10)[["name","points","team"]]

name  \
index                                                                      
Mark Flekken2024-11-04T20:00:00Z                            Mark Flekken   
Dean Henderson2024-11-02T17:30:00Z                        Dean Henderson   
Jordan Pickford2024-11-02T15:00:00Z                      Jordan Pickford   
Matz Sels2024-11-02T15:00:00Z                                  Matz Sels   
Arijanet Muric2024-11-02T15:00:00Z                        Arijanet Muric   
Ederson Santana de Moraes2024-11-02T15:00:00Z  Ederson Santana de Moraes   
André Onana2024-11-03T16:30:00Z                              André Onana   
Guglielmo Vicario2024-11-03T14:00:00Z                  Guglielmo Vicario   
Bernd Leno2024-11-04T20:00:00Z                                Bernd Leno   
David Raya Martin2024-11-02T12:30:00Z                  David Raya Martin   

                                                 points            team  
index                                                                    
Mark Flekken2024-11-04T20:00:00Z               3.757804       Brentford  
Dean Henderson2024-11-02T17:30:00Z             3.516444  Crystal Palace  
Jordan Pickford2024-11-02T15:00:00Z            3.392530         Everton  
Matz Sels2024-11-02T15:00:00Z                  3.361403   Nott'm Forest  
Arijanet Muric2024-11-02T15:00:00Z             3.243361         Ipswich  
Ederson Santana de Moraes2024-11-02T15:00:00Z  3.139257        Man City  
André Onana2024-11-03T16:30:00Z                3.016022         Man Utd  
Guglielmo Vicario2024-11-03T14:00:00Z          3.008410           Spurs  
Bernd Leno2024-11-04T20:00:00Z                 2.966050          Fulham  
David Raya Martin2024-11-02T12:30:00Z          2.883292         Arsenal

In [119]:
test[test["position"]=="FWD"].sort_values(by="points",ascending=False).head(10)[["name","points","team"]]

name  \
index                                                                                  
Ollie Watkins2024-11-03T14:00:00Z                                      Ollie Watkins   
Erling Haaland2024-11-02T15:00:00Z                                    Erling Haaland   
Chris Wood2024-11-02T15:00:00Z                                            Chris Wood   
Kai Havertz2024-11-02T12:30:00Z                                          Kai Havertz   
Matheus Santos Carneiro Da Cunha2024-11-02T17:3...  Matheus Santos Carneiro Da Cunha   
Nicolas Jackson2024-11-03T16:30:00Z                                  Nicolas Jackson   
Jørgen Strand Larsen2024-11-02T17:30:00Z                        Jørgen Strand Larsen   
Raúl Jiménez2024-11-04T20:00:00Z                                        Raúl Jiménez   
Jamie Vardy2024-11-02T15:00:00Z                                          Jamie Vardy   
George Hirst2024-11-02T15:00:00Z                                        George Hirst   

                                                      points           team  
index                                                                        
Ollie Watkins2024-11-03T14:00:00Z                   5.960358    Aston Villa  
Erling Haaland2024-11-02T15:00:00Z                  5.904990       Man City  
Chris Wood2024-11-02T15:00:00Z                      5.085697  Nott'm Forest  
Kai Havertz2024-11-02T12:30:00Z                     4.155948        Arsenal  
Matheus Santos Carneiro Da Cunha2024-11-02T17:3...  4.040393         Wolves  
Nicolas Jackson2024-11-03T16:30:00Z                 4.014294        Chelsea  
Jørgen Strand Larsen2024-11-02T17:30:00Z            3.692594         Wolves  
Raúl Jiménez2024-11-04T20:00:00Z                    3.692124         Fulham  
Jamie Vardy2024-11-02T15:00:00Z                     3.279927      Leicester  
George Hirst2024-11-02T15:00:00Z                    3.273398        Ipswich

In [120]:
test["points"].sort_values(ascending=False).head(50)

index
Mohamed Salah2024-11-02T15:00:00Z                         7.046866
Ollie Watkins2024-11-03T14:00:00Z                         5.960358
Erling Haaland2024-11-02T15:00:00Z                        5.904990
Bukayo Saka2024-11-02T12:30:00Z                           5.566477
Chris Wood2024-11-02T15:00:00Z                            5.085697
Bryan Mbeumo2024-11-04T20:00:00Z                          4.812529
Cole Palmer2024-11-03T16:30:00Z                           4.477835
Declan Rice2024-11-02T12:30:00Z                           4.459019
Brennan Johnson2024-11-03T14:00:00Z                       4.187138
Eberechi Eze2024-11-02T17:30:00Z                          4.182510
Kai Havertz2024-11-02T12:30:00Z                           4.155948
Matheus Santos Carneiro Da Cunha2024-11-02T17:30:00Z      4.040393
Jarrod Bowen2024-11-02T15:00:00Z                          4.021720
Nicolas Jackson2024-11-03T16:30:00Z                       4.014294
Mikkel Damsgaard2024-11-04T20:00:00Z                      3.893360
Dwight McNeil2024-11-02T15:00:00Z                         3.871607
Mark Flekken2024-11-04T20:00:00Z                          3.757804
Jørgen Strand Larsen2024-11-02T17:30:00Z                  3.692594
Raúl Jiménez2024-11-04T20:00:00Z                          3.692124
Trent Alexander-Arnold2024-11-02T15:00:00Z                3.686967
Bruno Borges Fernandes2024-11-03T16:30:00Z                3.686618
Anthony Gordon2024-11-02T12:30:00Z                        3.679647
Bernardo Veiga de Carvalho e Silva2024-11-02T15:00:00Z    3.669663
Rayan Aït-Nouri2024-11-02T17:30:00Z                       3.640290
Phil Foden2024-11-02T15:00:00Z                            3.583457
Joško Gvardiol2024-11-02T15:00:00Z                        3.541818
Dean Henderson2024-11-02T17:30:00Z                        3.516444
Ashley Young2024-11-02T15:00:00Z                          3.497327
Dejan Kulusevski2024-11-03T14:00:00Z                      3.464911
Luis Díaz2024-11-02T15:00:00Z                             3.422930
Callum Hudson-Odoi2024-11-02T15:00:00Z                    3.402004
Jordan Pickford2024-11-02T15:00:00Z                       3.392530
Matz Sels2024-11-02T15:00:00Z                             3.361403
Alex Iwobi2024-11-04T20:00:00Z                            3.331518
Ryan Yates2024-11-02T15:00:00Z                            3.295628
Jamie Vardy2024-11-02T15:00:00Z                           3.279927
George Hirst2024-11-02T15:00:00Z                          3.273398
Diogo Teixeira da Silva2024-11-02T15:00:00Z               3.270006
Adama Traoré2024-11-04T20:00:00Z                          3.267979
Arijanet Muric2024-11-02T15:00:00Z                        3.243361
Iliman Ndiaye2024-11-02T15:00:00Z                         3.241353
Dominic Calvert-Lewin2024-11-02T15:00:00Z                 3.232633
Ethan Pinnock2024-11-04T20:00:00Z                         3.232022
James Maddison2024-11-03T14:00:00Z                        3.223373
Moisés Caicedo Corozo2024-11-03T16:30:00Z                 3.208613
Gabriel Martinelli Silva2024-11-02T12:30:00Z              3.207811
Leif Davis2024-11-02T15:00:00Z                            3.206921
Antoine Semenyo2024-11-02T15:00:00Z                       3.188539
Vitaly Janelt2024-11-04T20:00:00Z                         3.181617
Liam Delap2024-11-02T15:00:00Z                            3.150306
Name: points, dtype: float64

In [121]:

feature_importance = pd.DataFrame(
    {"column": x.columns, "imp": model.feature_importances_}
).sort_values(
    "imp", ascending=False
)  #

In [122]:
feature_importance.head(50)

column   imp
71    opp mean team Goal scored all  6558
72  opp mean team Goal conceded all  6255
73        opp mean match_result all  6133
29                 mean ict_index 3  5027
4                     percent_value  4832
64        mean team Goal scored all  4792
66      mean team Goal conceded all  4760
26                mean creativity 3  4661
24                       mean bps 3  4639
62            mean match_result all  4487
38                        std bps 3  4472
30                 mean influence 3  4343
40                  std ict_index 3  4315
43                     std threat 3  4205
0                             value  4150
50            mean clean_sheets all  4105
39                 std creativity 3  4056
31                   mean minutes 3  3964
34                    mean threat 3  3939
21    opponent_last_season_position  3914
59                  mean threat all  3849
20                               GW  3772
49                     mean bps all  3762
41                  std influence 3  3761
60            mean total_points all  3756
52          mean goals_conceded all  3752
55               mean influence all  3740
48                   mean bonus all  3593
56                 mean minutes all  3565
42                    std minutes 3  3551
51              mean creativity all  3484
77                             week  3475
54               mean ict_index all  3469
44               std total_points 3  3356
67            ratio_goal_scored all  3278
36                     mean value 3  3274
35              mean total_points 3  3163
69      opp mean team Goal scored 3  3056
11                    creativity_ex  3042
19                      now_cost_ex  2998
8                   total_points_ex  2982
53            mean goals_scored all  2945
15                           bps_ex  2932
47                 mean assists all  2928
61                   mean value all  2822
70    opp mean team Goal conceded 3  2822
13                        threat_ex  2765
16                     ict_index_ex  2759
9                        minutes_ex  2739
12                     influence_ex  2708

In [123]:
feature_importance.tail(30)

column   imp
9                  minutes_ex  2739
12               influence_ex  2708
63    mean team Goal scored 3  2639
10          goals_conceded_ex  2622
76                       hour  2435
3        last_season_position  2428
27      mean goals_conceded 3  2133
14                   bonus_ex  1948
65  mean team Goal conceded 3  1850
17            clean_sheets_ex  1805
37        mean match_result 3  1622
7                  assists_ex  1608
68        ratio_goal_scored 3  1544
5               position rank  1414
6             goals_scored_ex  1398
18            yellow_cards_ex  1386
75                      month  1263
74                day_of week  1213
2                    was_home  1200
1                    position   891
46               mean saves 3   824
58         mean red_cards all   800
23               mean bonus 3   789
45                std value 3   766
25        mean clean_sheets 3   753
57         mean own_goals all   737
22             mean assists 3   568
33           mean red_cards 3   567
28        mean goals_scored 3   244
32           mean own_goals 3    73

#Save predictions

In [143]:
test_copy[test_copy["position"]=="DEF"][["name","team","minutes"]].to_csv(f"/content/gdrive/MyDrive/fplpredict/predicted_dataset/GW{gameweek}/defendetrs_minutes.csv")
test_copy[test_copy["position"]=="GKP"][["name","team","minutes"]].to_csv(f"/content/gdrive/MyDrive/fplpredict/predicted_dataset/GW{gameweek}/goalkeepers_minutes.csv")
test_copy[test_copy["position"]=="MID"][["name","team","minutes"]].to_csv(f"/content/gdrive/MyDrive/fplpredict/predicted_dataset/GW{gameweek}/midfielders_minutes.csv")
test_copy[test_copy["position"]=="FWD"][["name","team","minutes"]].to_csv(f"/content/gdrive/MyDrive/fplpredict/predicted_dataset/GW{gameweek}/forwards_minutes.csv")

In [124]:
test[test["position"]=="DEF"][["name","team","points","value"]].to_csv(f"/content/gdrive/MyDrive/fplpredict/predicted_dataset/GW{gameweek}/defenders_points.csv")
test[test["position"]=="GKP"][["name","team","points","value"]].to_csv(f"/content/gdrive/MyDrive/fplpredict/predicted_dataset/GW{gameweek}/goalkeepers_points.csv")
test[test["position"]=="MID"][["name","team","points","value"]].to_csv(f"/content/gdrive/MyDrive/fplpredict/predicted_dataset/GW{gameweek}/midfielders_points.csv")
test[test["position"]=="FWD"][["name","team","points","value"]].to_csv(f"/content/gdrive/MyDrive/fplpredict/predicted_dataset/GW{gameweek}/forwards_points.csv")